name: Build and run tests
on: [push]
jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ENVIRONMENT_MACOS: CC='clang' CXX='clang++'
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
  run:
    name: Test on ${{ matrix.os }} with python ${{ matrix.python-version }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-11]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: built_wheels

      - name: Install packages
        run: python -m pip install --no-index --find-links=./built_wheels yapyjit
      
      - name: Run tests
        run: python run_tests.py
